SAH/Models/Faq.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace SAH.Models
{
    public class Faq
    {
        [Key]
        public int FaqID { get; set; }
        public string Question { get; set; }
        public string Answer { get; set; }
        public bool Publish { get; set; }

        [ForeignKey("Department")]
        public int? DepartmentID { get; set; } 
        public virtual Department Department { get; set; }
    }

    public class FaqDto
    {
        [Key]
        [DisplayName("FAQ ID")]
        public int FaqID { get; set; }
        public string Question { get; set; }
        public string Answer { get; set; }
        public bool Publish { get; set; }
        public int? DepartmentID { get; set; }
        [DisplayName("Department")]
        public string DepartmentName { get; set; }

    }
}

SAH/Controllers/FaqController.cs
using SAH.Models;
using SAH.Models.ModelViews;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace SAH.Controllers
{
    public class FaqController : Controller
    {

        private JavaScriptSerializer jss = new JavaScriptSerializer();
        private static readonly HttpClient client;

        /// <summary>
        /// This allows us to access a pre-defined C# HttpClient 'client' variable for sending POST and GET requests to the data access layer.
        /// </summary>
        static FaqController()
        {
            HttpClientHandler handler = new HttpClientHandler()
            {
                AllowAutoRedirect = false,
                UseCookies = false
            };
            client = new HttpClient(handler);
            //change this to match your own local port number
            client.BaseAddress = new Uri("https://localhost:44378/api/");
            client.DefaultRequestHeaders.Accept.Add(
            new MediaTypeWithQualityHeaderValue("application/json"));
        }

        // GET: Faq/AdminList
        [HttpGet]
        [Authorize(Roles = "Admin")]
        public ActionResult AdminList()
        {
            string url = "FaqData/GetFaqs";
            HttpResponseMessage response = client.GetAsync(url).Result;
            if (response.IsSuccessStatusCode)
            {
                IEnumerable<FaqDto> faqs = response.Content.ReadAsAsync<IEnumerable<FaqDto>>().Result;
                return View(faqs);
            }
            else
            {
                return RedirectToAction("Error");
            }
        }

        // GET: Faq/Edit/5
        [HttpGet]
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int id)
        {
            //Model used to combine a faq object and departments list for dropdown
            EditFaq modelView = new EditFaq();

            //Get the current ParkingSpot object
            string url = "FaqData/FindFaq/" + id;
            HttpResponseMessage response = client.GetAsync(url).Result;

            if (response.IsSuccessStatusCode)
            {
                FaqDto SelectedFaq = response.Content.ReadAsAsync<FaqDto>().Result;
                modelView.Faq = SelectedFaq;
            }
            else
            {
                return RedirectToAction("Error");
            }

            //The view needs to be sent a list of all the Departments so the client can select a Department for FAQ in the view
            modelView.DepartmentsSelectList = GetDepartmentSelectList();

            return View(modelView);
        }

        // POST: Faq/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken()]
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int id, EditFaq faqInfo)
        {
            string url = "faqdata/updatefaq/" + id;

            HttpContent content = new StringContent(jss.Serialize(faqInfo.Faq));
            content.Headers.ContentType = new MediaTypeHeaderValue("application/json");
            HttpResponseMessage response = client.PostAsync(url, content).Result;

            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("AdminList");
            }
            else
            {
                return RedirectToAction("Error");
            }
        }

        // GET: Faq/Create
        [HttpGet]
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            //Model used to combine a faq object and departments list for dropdown
            EditFaq modelView = new EditFaq();

            // FAQ is empty for before creating new FAQ
            modelView.Faq = new FaqDto();

            //The view needs to be sent a list of all the Departments so the client can select a Department for FAQ in the view
            modelView.DepartmentsSelectList = GetDepartmentSelectList();

            return View(modelView);
        }

        // POST: Faq/Create
        [HttpPost]
        [ValidateAntiForgeryToken()]
        [Authorize(Roles = "Admin")]
        public ActionResult Create(EditFaq faqInfo)
        {
            string url = "faqdata/AddFaq";

            HttpContent content = new StringContent(jss.Serialize(faqInfo.Faq));
            content.Headers.ContentType = new MediaTypeHeaderValue("application/json");
            HttpResponseMessage response = client.PostAsync(url, content).Result;

            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("AdminList");
            }
            else
            {
                return RedirectToAction("Error");
            }
        }

        // GET: faq/DeleteConfirm/5
        [HttpGet]
        [Authorize(Roles = "Admin")]
        public ActionResult DeleteConfirm(int id)
        {
            //Get the current ParkingSpot object
            string url = "faqdata/FindFaq/" + id;
            HttpResponseMessage response = client.GetAsync(url).Result;

            if (response.IsSuccessStatusCode)
            {
                FaqDto SelectedFaq = response.Content.ReadAsAsync<FaqDto>().Result;
                return View(SelectedFaq);
            }
            else
            {
                return RedirectToAction("Error");
            }
        }

        // POST: faq/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken()]
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int id)
        {
            string url = "faqdata/deletefaq/" + id;
            //post body is empty
            HttpContent content = new StringContent("");
            HttpResponseMessage response = client.PostAsync(url, content).Result;

            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("AdminList");
            }
            else
            {
                return RedirectToAction("Error");
            }
        }

        // GET: Faq/PublicView
        [HttpGet]
        public ActionResult PublicView()
        {
            //Model used to combine a the faq list and the objects for the form 
            ViewFaq modelView = new ViewFaq();

            string url = "FaqData/GetPublicFaqs";
            HttpResponseMessage response = client.GetAsync(url).Result;
            if (response.IsSuccessStatusCode)
            {
                IEnumerable<FaqDto> faqs = response.Content.ReadAsAsync<IEnumerable<FaqDto>>().Result;
                modelView.FaqList = faqs;
            }
            else
            {
                return RedirectToAction("Error");
            }

            // FAQ is empty for before creating new FAQ
            modelView.newFaq = new FaqDto();

            //The view needs to be sent a list of all the Departments so the client can select a Department for FAQ in the view
            modelView.DepartmentsSelectList = GetDepartmentSelectList();

            return View(modelView);
        }

        // POST: Faq/PublicView
        [HttpPost]
        [ValidateAntiForgeryToken()]
        public ActionResult PublicView(ViewFaq faqInfo)
        {
            string url = "faqdata/AddFaq";

            HttpContent content = new StringContent(jss.Serialize(faqInfo.newFaq));
            content.Headers.ContentType = new MediaTypeHeaderValue("application/json");
            HttpResponseMessage response = client.PostAsync(url, content).Result;

            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("PublicView");
            }
            else
            {
                return RedirectToAction("Error");
            }
        }


        public ActionResult Error()
        {
            return View();
        }

        private SelectList GetDepartmentSelectList()
        {
            string url = "DepartmentData/GetDepartments/";
            HttpResponseMessage response = client.GetAsync(url).Result;
            IEnumerable<DepartmentDto> departmentsList = response.Content.ReadAsAsync<IEnumerable<DepartmentDto>>().Result;
            // Convert departmentsList to  SelectList
            SelectList departmentsSelectList = new SelectList(departmentsList, "DepartmentId", "DepartmentName");
            return departmentsSelectList;
        }
    }
}

SAH/Views/Faq/AdminList.cshtml
@model IEnumerable<SAH.Models.FaqDto>

@{
    ViewBag.Title = "FAQ List";
}

<h2>Frequently Asked Questions - Admin</h2>

<p>
    <span>
        @Html.ActionLink("Create New", "Create")

    </span>
    <span style="margin-left: 20px">
        @Html.ActionLink("Public View", "PublicView")

    </span>
</p>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Question)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Answer)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Publish)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DepartmentName)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Question)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Answer)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Publish)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DepartmentName)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.FaqID }) |
                @Html.ActionLink("Delete", "DeleteConfirm", new { id = item.FaqID })
            </td>
        </tr>
    }

</table>

SAH/Views/Faq/Create.cshtml
@model SAH.Models.ModelViews.EditFaq

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Faq</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Faq.Question, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Faq.Question, new { htmlAttributes = new { @class = "form-control", @style = "max-width: 100%" } })
            @Html.ValidationMessageFor(model => model.Faq.Question, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Faq.Answer, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @*@Html.EditorFor(model => model.Faq.Answer, new { htmlAttributes = new { @class = "form-control" } })*@
            @Html.TextAreaFor(model => model.Faq.Answer, new { cols = 100, @rows = 3, @class = "form-control", @style = "max-width: 100%" })
            @Html.ValidationMessageFor(model => model.Faq.Answer, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Faq.DepartmentID, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(x => x.Faq.DepartmentID, Model.DepartmentsSelectList, "-- Please Select --", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Faq.DepartmentID, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-check">
        @Html.LabelFor(model => model.Faq.Publish, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.Faq.Publish)
                @Html.ValidationMessageFor(model => model.Faq.Publish, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "AdminList")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SAH/Views/Faq/DeleteConfirm.cshtml
@model SAH.Models.FaqDto

@{
    ViewBag.Title = "DeleteConfirm";
}

<h3>Are you sure you want to delete this FAQ?</h3>
<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Question)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Question)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Answer)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Answer)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Publish)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Publish)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DepartmentID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DepartmentID)
        </dd>

    </dl>


    @using (Html.BeginForm("Delete", "Faq", new { id = Model.FaqID }))
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> | 
            @Html.ActionLink("Back to List", "AdminList")

        </div>
    }
    @*@using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }*@
</div>

SAH/Views/Faq/Edit.cshtml
@model SAH.Models.ModelViews.EditFaq

@{
    ViewBag.Title = "Edit FAQ";
}

<h2>Edit FAQ</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>FaqDto</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Faq.FaqID)

        <div class="form-group">
            @Html.LabelFor(model => model.Faq.Question, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Faq.Question, new { htmlAttributes = new { @class = "form-control", @style = "max-width: 100%" } })
                @Html.ValidationMessageFor(model => model.Faq.Question, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Faq.Answer, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.Faq.Answer, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.TextAreaFor(model => model.Faq.Answer, new { cols = 100, @rows = 3, @class = "form-control", @style = "max-width: 100%" })
                @Html.ValidationMessageFor(model => model.Faq.Answer, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Faq.DepartmentID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(x => x.Faq.DepartmentID, Model.DepartmentsSelectList, "-- Please Select --", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Faq.DepartmentID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-check">
            @Html.LabelFor(model => model.Faq.Publish, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Faq.Publish)
                    @Html.ValidationMessageFor(model => model.Faq.Publish, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "AdminList")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SAH/Views/Faq/PublicView.cshtml
@model SAH.Models.ModelViews.ViewFaq

@{
    ViewBag.Title = "FAQ List";
}

<h2>Frequently Asked Questions</h2>

<table class="table">

    @foreach (var faq in Model.FaqList)
    {
        <div class="panel-group">
            <div class="panel panel-info">
                <div class="panel-heading">@Html.DisplayFor(modelItem => faq.Question)</div>
                <div class="panel-body">@Html.DisplayFor(modelItem => faq.Answer)</div>
            </div>
        </div>
    }

</table>

<h2>Submit new Question</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.newFaq.Question, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.newFaq.Question, new { cols = 100, @rows = 3, @class = "form-control", @style = "max-width: 80%" })
                @Html.ValidationMessageFor(model => model.newFaq.Question, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.newFaq.DepartmentID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(x => x.newFaq.DepartmentID, Model.DepartmentsSelectList, "Please Select", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.newFaq.DepartmentID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Submit" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}