SAH/Models/EmployeeApplicant.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;


namespace SAH.Models
{
    public class EmployeeApplicant
    {
        [Key]
        public int EmployeeApplicantId { get; set; }

        //Applicant reason
        public string Reason { get; set; }

        //THe applicant will be a user
        [ForeignKey("ApplicationUser")]
        public string Id { get; set; }
        public virtual ApplicationUser ApplicationUser { get; set; }

        //Applicant will apply for course
        [ForeignKey("Courses")]
        public int CourseId { get; set; }
        public virtual Courses Courses { get; set; }

        //Applicant has a role
       // [ForeignKey("Role")]
        //public int RoleId { get; set; }
       // public virtual Role Role { get; set; }
    }
    public class EmployeeApplicantDto
    {
        [DisplayName("Registration Number")]
        public int EmployeeApplicantId { get; set; }

        //Applicant reason
        public string Reason { get; set; }
        //Applicant is a user
        public string Id { get; set; }

        //Applicant linked to a course
        public int CourseId { get; set; }

        //Applicant has a role
       // public int RoleId { get; set; }
    }
}

SAH/Controllers/EmployeeApplicantController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Diagnostics;
using System.Web.Script.Serialization;
using SAH.Models;
using SAH.Models.ModelViews;
using System.IO;
using Microsoft.AspNet.Identity;

namespace SAH.Controllers
{
    public class EmployeeApplicantController : Controller

    {
        private JavaScriptSerializer jss = new JavaScriptSerializer();
        private static readonly HttpClient client;


        static EmployeeApplicantController()
        {
            HttpClientHandler handler = new HttpClientHandler()
            {
                AllowAutoRedirect = false
            };
            client = new HttpClient(handler);

            client.BaseAddress = new Uri("https://localhost:44378/api/");
            client.DefaultRequestHeaders.Accept.Add(
            new MediaTypeWithQualityHeaderValue("application/json"));

        }

        /// Grabs the authentication credentials which are sent to the Controller.

        private void GetApplicationCookie()
        {
            string token = "";

            client.DefaultRequestHeaders.Remove("Cookie");
            if (!User.Identity.IsAuthenticated) return;
            HttpCookie cookie = System.Web.HttpContext.Current.Request.Cookies.Get(".AspNet.ApplicationCookie");
            if (cookie != null) token = cookie.Value;

            //collect token as it is submitted to the controller
            //use it to pass along to the WebAPI.
            Debug.WriteLine("Token Submitted is : " + token);
            if (token != "") client.DefaultRequestHeaders.Add("Cookie", ".AspNet.ApplicationCookie=" + token);

            return;
        }

        // GET: EmployeeApplicant/List
        [Authorize(Roles = "Admin")]
        public ActionResult List()
        {
            GetApplicationCookie();

            

            string url = "EmployeeApplicantsData/GetAllApplications";
            HttpResponseMessage response = client.GetAsync(url).Result;
            if (response.IsSuccessStatusCode)
            {
                IEnumerable<ShowEmployeeApplicant> SelectedApplications = response.Content.ReadAsAsync<IEnumerable<ShowEmployeeApplicant>>().Result;
                return View(SelectedApplications);
            }
            else
            {
                return RedirectToAction("Error");
            }
        }

        // GET: EmployeeApplicant/Details/5
        [Authorize(Roles = "Admin,Staff")]
        public ActionResult Details(int id)
        {
            GetApplicationCookie();

            ShowEmployeeApplicant ShowEmployeeApplicant = new ShowEmployeeApplicant();
            ShowEmployeeApplicant.isadmin = User.IsInRole("Admin");

            //Find the Employee application from the database
            string url = "EmployeeApplicantsData/FindApplication/" + id;
            HttpResponseMessage response = client.GetAsync(url).Result;

            if (response.IsSuccessStatusCode)
            {
                EmployeeApplicantDto SelectedApplication = response.Content.ReadAsAsync<EmployeeApplicantDto>().Result;
                ShowEmployeeApplicant.EmployeeApplicant = SelectedApplication;

                //Associated Employee Application with User
                url = "EmployeeApplicantsData/GetApplicationUser/" + id;
                response = client.GetAsync(url).Result;
                ApplicationUserDto SelectedUser = response.Content.ReadAsAsync<ApplicationUserDto>().Result;
                ShowEmployeeApplicant.User = SelectedUser;

                //Associated Employee application with Course
                url = "EmployeeApplicantsData/GetCourseForApplication/" + id;
                response = client.GetAsync(url).Result;
                CoursesDto SelectedCourse = response.Content.ReadAsAsync<CoursesDto>().Result;
                ShowEmployeeApplicant.Courses = SelectedCourse;

                return View(ShowEmployeeApplicant);
            }
            else
            {
                return RedirectToAction("Error");
            }
        }

        // GET: EmployeeApplicant/Create
        [Authorize(Roles = "Admin,Staff")]
        public ActionResult Create()
        {
            GetApplicationCookie();
            //Get all the users for dropdown list
            EditEmployeeApplicant EditEmployeeApplicant = new EditEmployeeApplicant();
            string url = "EmployeeApplicantsData/GetUsers";
            HttpResponseMessage response = client.GetAsync(url).Result;

            IEnumerable<ApplicationUserDto> SelectedUsers = response.Content.ReadAsAsync<IEnumerable<ApplicationUserDto>>().Result;
            EditEmployeeApplicant.AllUsers = SelectedUsers;

            User.Identity.GetUserId();

            //Get all the Courses for dropdown list
            url = "EmployeeApplicantsData/GetCourses";
            response = client.GetAsync(url).Result;

            IEnumerable<CoursesDto> SelectedCourses = response.Content.ReadAsAsync<IEnumerable<CoursesDto>>().Result;
            EditEmployeeApplicant.AllCourses = SelectedCourses;

            return View(EditEmployeeApplicant);
        }

        // POST: EmployeeApplicant/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,Staff")]
        public ActionResult Create(EmployeeApplicant EmployeeApplicant)
        {
            GetApplicationCookie();

            

            //Add a new application to the database
            string url = "EmployeeApplicantsData/AddApplication";
            HttpContent content = new StringContent(jss.Serialize(EmployeeApplicant));

            content.Headers.ContentType = new MediaTypeHeaderValue("application/json");
            HttpResponseMessage response = client.PostAsync(url, content).Result;

            if (response.IsSuccessStatusCode)
            {

                int EmployeeApplicantId = response.Content.ReadAsAsync<int>().Result;
                return RedirectToAction("Details", new { id = EmployeeApplicantId });
            }
            else
            {
                return RedirectToAction("Error");
            }
        }

        // GET: EmployeeApplicant/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int id)
        {
            EditEmployeeApplicant NewEmployeeApplicant = new EditEmployeeApplicant();

            //Get the selected employee application from the database
            string url = "EmployeeApplicantsData/FindApplication/" + id;
            HttpResponseMessage response = client.GetAsync(url).Result;

            if (response.IsSuccessStatusCode)
            {
                EmployeeApplicantDto SelectedApplication = response.Content.ReadAsAsync<EmployeeApplicantDto>().Result;
                NewEmployeeApplicant.EmployeeApplicant = SelectedApplication;
            }
            else
            {
                return RedirectToAction("Error");
            }

            //Get all users from the database for dropdown list
            url = "EmployeeApplicantsData/GetUsers";
            response = client.GetAsync(url).Result;
            if (response.IsSuccessStatusCode)
            {
                IEnumerable<ApplicationUserDto> SelectedUsers = response.Content.ReadAsAsync<IEnumerable<ApplicationUserDto>>().Result;
                NewEmployeeApplicant.AllUsers = SelectedUsers;
            }
            else
            {
                return RedirectToAction("Error");
            }

            //Get all courses from the database for dropdown list
            url = "EmployeeApplicantsData/GetCourses";
            response = client.GetAsync(url).Result;
            if (response.IsSuccessStatusCode)
            {
                IEnumerable<CoursesDto> SelectedJobs = response.Content.ReadAsAsync<IEnumerable<CoursesDto>>().Result;
                NewEmployeeApplicant.AllCourses = SelectedJobs;
            }
            else
            {
                return RedirectToAction("Error");
            }
            return View(NewEmployeeApplicant);

        }

        // POST: EmployeeApplicant/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int id, EmployeeApplicant EmployeeApplicant)
        {
            string url = "EmployeeApplicantsData/UpdateApplication/" + id;

            HttpContent content = new StringContent(jss.Serialize(EmployeeApplicant));
            content.Headers.ContentType = new MediaTypeHeaderValue("application/json");
            HttpResponseMessage response = client.PostAsync(url, content).Result;

            if (response.IsSuccessStatusCode)
            {

                return RedirectToAction("Details", new { id = EmployeeApplicant.EmployeeApplicantId });
            }
            else
            {
                return RedirectToAction("Error");
            }

        }

        // GET: EmployeeApplicant/Delete/5
        [HttpGet]
        [Authorize(Roles = "Admin")]
        public ActionResult DeleteConfirm(int id)
        {
            //Get current employee application from the database
            string url = "EmployeeApplicantsData/FindApplication/" + id;
            HttpResponseMessage response = client.GetAsync(url).Result;
            //Can catch the status code (200 OK, 301 REDIRECT), etc.
            //Debug.WriteLine(response.StatusCode);
            if (response.IsSuccessStatusCode)
            {
                //Put data into EmployeeApplicant data transfer object
                EmployeeApplicantDto SelectedApplication = response.Content.ReadAsAsync<EmployeeApplicantDto>().Result;
                return View(SelectedApplication);
            }
            else
            {
                return RedirectToAction("Error");
            }
        }

        // POST: EmployeeApplicant/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken()]

SAH/Views/EmployeeApplicant/Create.cshtml
@model SAH.Models.ModelViews.EditEmployeeApplicant

@{
    ViewBag.Title = "Create";
}
<h2>Internal Education Portal</h2>


<form action="/EmployeeApplicant/Create" method="post" name="create">
    @Html.AntiForgeryToken()
    <div class="form-horizontal">

        <h4>Register for Course</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })


        <div class="form-group">
            <p class="control-label col-md-2"><b>Employee</b></p>
            <div class="col-md-10">


                <select name="EmployeeApplicant.Id">
                    @foreach (var User in Model.AllUsers)
                    {
                        <option value="@User.Id">@User.FirstName @User.LastName</option>
                    }
                </select>
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.EmployeeApplicant.CourseId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <select name="EmployeeApplicant.CourseId">
                    @foreach (var Course in Model.AllCourses)
                    {
                        <option value="@Course.CourseId">@Course.CourseName</option>
                    }
                </select>
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.EmployeeApplicant.Reason, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmployeeApplicant.Reason, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EmployeeApplicant.Reason, "", new { @class = "text-danger" })
            </div>
        </div>




        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" onclick="verifyTicket();" class="btn btn-default" />
            </div>
        </div>

</form>

<div>
    @Html.ActionLink("Back to List", "List")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SAH/Views/EmployeeApplicant/DeleteConfirm.cshtml
@model SAH.Models.EmployeeApplicantDto

@{
    ViewBag.Title = "View";
}

<h2>Internal Education Portal</h2>

<h3>Are you sure you want to delete this Employee Application?</h3>
<div>
    <h4>Delete Employee Application</h4>
    <hr />
    <dl class="dl-horizontal">
    </dl>

    @using (Html.BeginForm("Delete", "EmployeeApplicant", new { Id = Model.CourseId }))
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "List")
        </div>
    }
</div>

SAH/Views/EmployeeApplicant/Details.cshtml
@model SAH.Models.ModelViews.ShowEmployeeApplicant

@{
    ViewBag.Title = "Details";
}

<h2>Internal Education Portal</h2>
<div>
    <h4>Employee Application Details</h4>
    <hr />
    <dl class="dl-horizontal Ticket">

        <div>
            <dt>
                @Html.DisplayNameFor(model => model.EmployeeApplicant.EmployeeApplicantId)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.EmployeeApplicant.EmployeeApplicantId)
            </dd>
            <dt>
                Employee Name
            </dt>

            <dd>
                @Html.DisplayFor(model => model.User.FirstName)  @Html.DisplayFor(model => model.User.LastName)
            </dd>
            <dt>
                Employee Number
            </dt>

            <dd>
                @Html.DisplayFor(model => model.User.EmployeeNumber)
            </dd>
            <dt>
                Email
            </dt>

            <dd>
                @Html.DisplayFor(model => model.User.Email)
            </dd>

            <dt>
                Course Registered
            </dt>
            <dd>
                @Html.ActionLink(Model.Courses.CourseCode, "Details", "Courses", new { id = Model.Courses.CourseId }, new { })
                @Html.ActionLink(Model.Courses.CourseName, "Details", "Courses", new { id = Model.Courses.CourseId }, new { })
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.EmployeeApplicant.Reason)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.EmployeeApplicant.Reason)
            </dd>
        </div>




    </dl>
</div>
<p>


    @if (Model.isadmin)
    {
    @Html.ActionLink(" Back |", "List") 
    @Html.ActionLink(" Edit |", "Edit", new { id = Model.EmployeeApplicant.EmployeeApplicantId })
    @Html.ActionLink(" Delete ", "DeleteConfirm", new { id = Model.EmployeeApplicant.EmployeeApplicantId })
    }
</p>

SAH/Views/EmployeeApplicant/Edit.cshtml
@model SAH.Models.ModelViews.EditEmployeeApplicant

@{
    ViewBag.Title = "Edit";
}

<h4>Edit Application</h4>


<form action="/EmployeeApplicant/Edit/@Model.EmployeeApplicant.EmployeeApplicantId" method="post" name="createTicket">
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.EmployeeApplicant.EmployeeApplicantId)
       

        <div class="form-group">
            @Html.LabelFor(model => model.EmployeeApplicant.Id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <select name="EmployeeApplicant.Id">
                    @foreach (var user in Model.AllUsers)
                    {
                        string selected = "";
                        if (Model.EmployeeApplicant.Id == user.Id)
                        {
                            selected = "";
                        }
                        <option value="@user.Id" @selected>@user.FirstName @user.LastName</option>
                    }
                </select>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmployeeApplicant.CourseId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <select name="EmployeeApplicant.CourseId">
                    @foreach (var Course in Model.AllCourses)
                    {
                        string selected = "";
                        if (Model.EmployeeApplicant.CourseId == Course.CourseId)
                        {
                            selected = "";
                        }
                        <option value="@Course.CourseId" @selected>@Course.CourseName </option>
                    }
                </select>
            </div>
        </div>
            <div class="form-group">
                @Html.LabelFor(model => model.EmployeeApplicant.Reason, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.EmployeeApplicant.Reason, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.EmployeeApplicant.Reason, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" onclick="verifyTicket();" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    @Html.ActionLink("Back to List", "List")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SAH/Views/EmployeeApplicant/List.cshtml
@model IEnumerable<SAH.Models.ModelViews.ShowEmployeeApplicant>

@{
    ViewBag.Title = "List";
}

<h2>List of Employee Applications</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            Employee Name
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Courses.CourseName)
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.User.FirstName) @Html.DisplayFor(modelItem => item.User.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Courses.CourseName)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.EmployeeApplicant.EmployeeApplicantId }) |
                @Html.ActionLink("Details", "Details", new { id = item.EmployeeApplicant.EmployeeApplicantId }) |
                @Html.ActionLink("Delete", "DeleteConfirm", new { id = item.EmployeeApplicant.EmployeeApplicantId })
            </td>
        </tr>
    }

</table>