SAH/Models/Speciality.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SAH.Models
{
    public class Speciality
    {
        [Key]
        public int SpecialityId { get; set; }
        public string SpecialityName { get; set; }
        public ICollection<ApplicationUser> Users { get; set; }
    }

    public class SpecialityDto
    {
        [DisplayName("Speciality ID")]
        public int SpecialityId { get; set; }
        [DisplayName("Speciality Name")]
        [Required(ErrorMessage = "Please Enter a Speciality Name.")]
        public string SpecialityName { get; set; }
    }
}

SAH/Controllers/SpecialityController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using SAH.Models;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Diagnostics;
using System.Web.Script.Serialization;

namespace SAH.Controllers
{
    [Authorize(Roles = "Admin")]
    public class SpecialityController : Controller
    {
        //Http Client is the proper way to connect to a webapi
        //https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient?view=net-5.0

        private JavaScriptSerializer jss = new JavaScriptSerializer();
        private static readonly HttpClient client;

        static SpecialityController()
        {
            HttpClientHandler handler = new HttpClientHandler()
            {
                AllowAutoRedirect = false,
                //Cookies are manually set in RequestHeader
                UseCookies = false
            };

            client = new HttpClient(handler);
            Debug.WriteLine(handler);
            Debug.WriteLine(client);
            client.BaseAddress = new Uri("https://localhost:44378/api/");
            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

            //client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", ACCESS_TOKEN);
        }

        /// <summary>
        /// Get the authentication credentials from the cookies.
        /// Remember this is not considered a proper authentication technique for the webAPI
        /// </summary>
        private void GetApplicationCookie()
        {
            string token = "";
            //Reset cookies in HTTP client before get a new one.
            client.DefaultRequestHeaders.Remove("Cookie");
            if (!User.Identity.IsAuthenticated) return;

            HttpCookie cookie = System.Web.HttpContext.Current.Request.Cookies.Get(".AspNet.ApplicationCookie");
            if (cookie != null) token = cookie.Value;

            //Collect token and pass it to the WebAPI
            Debug.WriteLine("Token submitted is : " + token);
            if (token != "") client.DefaultRequestHeaders.Add("Cookie", ".AspNet.ApplicationCookie=" + token);

            return;
        }

        // GET: Speciality/List
        [AllowAnonymous]
        [HttpGet]
        public ActionResult List()
        {
            string url = "specialitydata/getspecialities";
            Debug.WriteLine(client.GetAsync(url).Result);
            HttpResponseMessage response = client.GetAsync(url).Result;
            if (response.IsSuccessStatusCode)
            {
                IEnumerable<SpecialityDto> SelectedSpecialities = response.Content.ReadAsAsync<IEnumerable<SpecialityDto>>().Result;
                return View(SelectedSpecialities);
            }
            else
            {
                return RedirectToAction("Error");
            }
        }

        // GET: Speciality/Details/5
        [AllowAnonymous]
        public ActionResult Details(int id)
        {
            string url = "specialitydata/findspeciality/" + id;
            HttpResponseMessage response = client.GetAsync(url).Result;
            //Can catch the status code (200 OK, 301 REDIRECT), etc.
            //Debug.WriteLine(response.StatusCode);
            if (response.IsSuccessStatusCode)
            {
                //Put data into speciality data transfer object
                SpecialityDto SelectedSpeciality = response.Content.ReadAsAsync<SpecialityDto>().Result;
                return View(SelectedSpeciality);
            }
            else
            {
                return RedirectToAction("Error");
            }
        }

        // GET: Speciality/Create
        public ActionResult Create()
        {
            SpecialityDto Speciality = new SpecialityDto();
            return View(Speciality);
        }

        // POST: Speciality/Create
        [HttpPost]
        [ValidateAntiForgeryToken()]
        public ActionResult Create(Speciality SpecialityInfo)
        {
            //Pass along authentication credential in http request
            GetApplicationCookie();

            //Debug.WriteLine(SpecialityInfo.SpecialityID);
            string url = "specialitydata/addspeciality";
            //Debug.WriteLine(jss.Serialize(SpecialityInfo));
            HttpContent content = new StringContent(jss.Serialize(SpecialityInfo));
            content.Headers.ContentType = new MediaTypeHeaderValue("application/json");
            HttpResponseMessage response = client.PostAsync(url, content).Result;
            Debug.WriteLine(response);

            if (response.IsSuccessStatusCode)
            {
                int specialityid = response.Content.ReadAsAsync<int>().Result;
                return RedirectToAction("Details", new { id = specialityid });
            }
            else
            {
                return RedirectToAction("Error");
            }
        }

        // GET: Speciality/Edit/5
        public ActionResult Edit(int id)
        {
            string url = "specialitydata/findspeciality/" + id;
            HttpResponseMessage response = client.GetAsync(url).Result;
            //Can catch the status code (200 OK, 301 REDIRECT), etc.
            //Debug.WriteLine(response.StatusCode);
            if (response.IsSuccessStatusCode)
            {
                //Put data into speciality data transfer object
                SpecialityDto SelectedSpeciality = response.Content.ReadAsAsync<SpecialityDto>().Result;
                return View(SelectedSpeciality);
            }
            else
            {
                return RedirectToAction("Error");
            }
        }

        // POST: Speciality/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken()]
        public ActionResult Edit(int id, Speciality SpecialityInfo)
        {
            //Pass along authentication credential in http request
            GetApplicationCookie();

            //Debug.WriteLine(SpecialityInfo.SpecialityID);
            string url = "specialitydata/updatespeciality/" + id;
            //Debug.WriteLine(jss.Serialize(SpecialityInfo));
            HttpContent content = new StringContent(jss.Serialize(SpecialityInfo));
            content.Headers.ContentType = new MediaTypeHeaderValue("application/json");
            HttpResponseMessage response = client.PostAsync(url, content).Result;
            Debug.WriteLine(response);
            if (response.IsSuccessStatusCode)
            {

                return RedirectToAction("Details", new { id = id });
            }
            else
            {
                return RedirectToAction("Error");
            }
        }

        // GET: Speciality/DeleteConfirm/5
        [HttpGet]
        public ActionResult DeleteConfirm(int id)
        {
            string url = "specialitydata/findspeciality/" + id;
            HttpResponseMessage response = client.GetAsync(url).Result;
            //Can catch the status code (200 OK, 301 REDIRECT), etc.
            //Debug.WriteLine(response.StatusCode);
            if (response.IsSuccessStatusCode)
            {
                //Put data into speciality data transfer object
                SpecialityDto SelectedSpeciality = response.Content.ReadAsAsync<SpecialityDto>().Result;
                return View(SelectedSpeciality);
            }
            else
            {
                return RedirectToAction("Error");
            }
        }

        // POST: Speciality/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken()]
        public ActionResult Delete(int id)
        {
            //Pass along authentication credential in http request
            GetApplicationCookie();

            string url = "specialitydata/deletespeciality/" + id;
            //post body is empty
            HttpContent content = new StringContent("");
            HttpResponseMessage response = client.PostAsync(url, content).Result;
            //Can catch the status code (200 OK, 301 REDIRECT), etc.
            //Debug.WriteLine(response.StatusCode);
            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("List");
            }
            else
            {
                return RedirectToAction("Error");
            }
        }

        public ActionResult Error()
        {
            return View();
        }
    }

}

SAH/Views/Speciality/Create.cshtml
@model SAH.Models.SpecialityDto

@{
    ViewBag.Title = "Create";
}

<h2>Create Speciality</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Speciality</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.SpecialityName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SpecialityName, new { htmlAttributes = new { @class = "form-control", Name = "SpecialityName" } })
                @Html.ValidationMessageFor(model => model.SpecialityName, "", new { @class = "text-danger", data_valmsg_for = "SpecialityName" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "List")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SAH/Views/Speciality/DeleteConfirm.cshtml
@model SAH.Models.SpecialityDto
@{
    ViewBag.Title = "DeleteConfirm";
}

<h2>DeleteConfirm</h2>

<h3>Are you sure you want to delete this?</h3>
@using (Html.BeginForm("Delete", "Speciality", new { id = Model.SpecialityId }))
{
    @Html.AntiForgeryToken()

    <div class="form-actions no-color">
        <input type="submit" value="Delete" class="btn btn-default" />
    </div>
}
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.SpecialityId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SpecialityId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SpecialityName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SpecialityName)
        </dd>

    </dl>
</div>
<div>
    @Html.ActionLink("Back to List", "List")
</div>

SAH/Views/Speciality/Details.cshtml
@model SAH.Models.SpecialityDto

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Speciality</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.SpecialityId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SpecialityId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.SpecialityName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SpecialityName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.SpecialityId }) |
    @Html.ActionLink("Back to List", "List")
</p>

SAH/Views/Speciality/Edit.cshtml
@model SAH.Models.SpecialityDto

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Speciality</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.SpecialityId, new { Name = "SpecialityId" })

        <div class="form-group">
            @Html.LabelFor(model => model.SpecialityName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SpecialityName, new { htmlAttributes = new { @class = "form-control", Name = "SpecialityName" } })
                @Html.ValidationMessageFor(model => model.SpecialityName, "", new { @class = "text-danger", data_valmsg_for = "SpecialityName" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "List")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SAH/Views/Speciality/List.cshtml
@model IEnumerable<SAH.Models.SpecialityDto>

@{
    ViewBag.Title = "List";
}

<h2>Speciality List</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<div style="overflow:auto">
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.SpecialityId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SpecialityName)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.SpecialityId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SpecialityName)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.SpecialityId }) |
                    @Html.ActionLink("Details", "Details", new { id = item.SpecialityId }) |
                    @Html.ActionLink("Delete", "DeleteConfirm", new { id = item.SpecialityId })
                </td>
            </tr>
        }

    </table>
</div>